### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fast-food-inception** [victormajida/project-time-tracker#1]
Hey there, I'd love to see the ability to actually pull that timer into code for say, discord rich presence where I can share the total amount of time I've been working on a project.

**Comment by victormajida** [comment]
Hey, sure. So are you thinking something like a copy button where the time gets copied to the clipboard? Or something different? 
Keep in mind the relevant times for this (I'd say total days & total real time) right now are stored in ptt.json as days number & a unix timestamp, respectively.

**Comment by echoless3484** [comment]
Just signed into my main account, i'm not that great at GDScript so i'll try to explain to the best of my ability. Here's what the code could look like, taking from vaporvees discord rpc extension

```
func _ready():
  DiscordRPC.app_id = hidden # Application ID
  DiscordRPC.details = "Freedrive: Los Injurious by Echoless"
  DiscordRPC.state = "Testing Freedrive"

  DiscordRPC.large_image = "image"

  DiscordRPC.start_timestamp = int(pttTime()) # "02:46 elapsed"
```

pttTime at the very end would be the total time spent in the project, as a unix timestamp

**Comment by victormajida** [comment]
Oh I see. Ok how about something like that:

`PTT.tracking_start_time()` # returns the date timestamp of when tracking started.

`PTT.total_active_time()` # returns the total (combined sessions) time integer.
`PTT.total_active_time_string()` # "6 hours 2 minutes elapsed"
`PTT.total_active_time_string("gone by")` # just a suffix change: "6 hours 2 minutes gone by"

`PTT.total_period()` # returns the integer of total days of work on the project.
`PTT.total_period_string()` # returns the total days of work on the project "1 month 3 days... elapsed"
`PTT.total_period_string("gone by")` # same as above, suffix change.

In the case of `DiscordRPC.start_timestamp`, I think `PTT.tracking_start_time()` is what you'd use.

Please keep in mind the value that would be returned by `PTT.tracking_start_time()` would just be as the function name states, the overall time since tracking started, not the actual days of work on the project nor the combined real time. For those you can then use the other functions, but I'm not sure how with DiscordRPC.

Would that work?

**Comment by echoless3484** [comment]
> Oh I see. Ok how about something like that:
> 
> `PTT.tracking_start_time()` # returns the date timestamp of when tracking started.
> 
> `PTT.total_active_time()` # returns the total (combined sessions) time integer.
> `PTT.total_active_time_string()` # "6 hours 2 minutes elapsed"
> `PTT.total_active_time_string("gone by")` # just a suffix change: "6 hours 2 minutes gone by"
> 
> `PTT.total_period()` # returns the integer of total days of work on the project.
> `PTT.total_period_string()` # returns the total days of work on the project "1 month 3 days... elapsed"
> `PTT.total_period_string("gone by")` # same as above, suffix change.
> 
> In the case of `DiscordRPC.start_timestamp`, I think `PTT.tracking_start_time()` is what you'd use.
> 
> Please keep in mind the value that would be returned by `PTT.tracking_start_time()` would just be as the function name states, the overall time since tracking started, not the actual days of work on the project nor the combined real time. For those you can then use the other functions, but I'm not sure how with DiscordRPC.
> 
> Would that work?

This is fantastic, it will 100% work!

**Comment by victormajida** [comment]
[Here](https://github.com/victormajida/project-time-tracker/releases/tag/v0.2) you go.
Apologies for the late reply. Had a lot to work on lately.
Let me know if all goes well.

**Comment by echoless3484** [comment]
> [Here](https://github.com/victormajida/project-time-tracker/releases/tag/v0.2) you go. Apologies for the late reply. Had a lot to work on lately. Let me know if all goes well.

Not quite sure if it works because of a heck load of errors, here they are below.
```res://addons/project_time_tracker/PTTUtils.gd:20 - Invalid set index '_data' (on base: 'Nil') with value of type 'Dictionary'.
  res://addons/project_time_tracker/ptt_object.gd:13 - Invalid get index 'lo' (on base: 'Dictionary').
  Couldn't launch Project Time Tracker. Data file empty!
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:33 - Invalid get index 'tt' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_object.gd:27 - Invalid get index 'st' (on base: 'Dictionary').
  res://addons/project_time_tracker/ptt_dock.gd:37 - Invalid type in function 'bb_text' in base 'GDScript'. Cannot convert argument 2 from Nil to float.
  res://addons/project_time_tracker/ptt_object.gd:36 - Invalid get index 'st' (on base: 'Dictionary').```

I did let the error repeat itself for about 5 seconds to see if it would resolve itself, this happened after I enabled the plugin. I'm fairly certain the first 2 lines happened after installing the plugin but not enabling it.

**Comment by victormajida** [comment]
[Fixed](https://github.com/victormajida/project-time-tracker/releases/tag/0.2.1)
The issue was when trying to load the data without finding the ptt.json file. The code will now properly create it if it doesn't find it.
